#! /usr/bin/env bash

bspc config border_width        2
bspc config window_gap         12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config click_to_focus      true

bspc monitor VGA-1 -d I II III IV V VI VII VIII IX X
bspc monitor HDMI-1 -d im web web2

bspc rule -a \*:scratchpad sticky=on state=floating

autorandr --change

panel &

tint2 &
